spring:
  application:
    name: spring-micrometer-observation


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  server:
    port: 8081